spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_data_study?useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true